SEQLEN_RATIO="4.0" FLASH_ATTN="1" python qlora.py \
    --model_name_or_path meta-llama/Llama-2-13b-hf \
    --output_dir ./output/webllama2_qlora_ctx14000_gen2000-13b \
    --max_memory_MB 81000 \
    --logging_steps 10 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 100 \
    --save_total_limit 40 \
    --evaluation_strategy steps \
    --eval_dataset_size 100 \
    --max_eval_samples 100 \
    --per_device_eval_batch_size 1 \
    --max_new_tokens 0 \
    --dataloader_num_workers 4 \
    --group_by_length \
    --logging_strategy steps \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --lora_r 64 \
    --lora_alpha 16 \
    --lora_modules all \
    --double_quant \
    --quant_type nf4 \
    --bf16 \
    --bits 4 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type constant \
    --gradient_checkpointing \
    --dataset ./resources/oasst_gpt_9k.jsonl \
    --dataset_format funcgpt_result \
    --source_max_len 14000 \
    --target_max_len 2000 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --max_steps 500 \
    --eval_steps 100 \
    --learning_rate 0.0001 \
    --adam_beta2 0.999 \
    --max_grad_norm 0.3 \
    --lora_dropout 0.05 \
    --weight_decay 0.0 \
    --use_auth_token True \
    --seed 0
